#!/bin/sh
### run example GISTIC analysis

## output directory
echo --- creating output directory ---
basedir=`pwd`/GISTIC_hapmap_results
mkdir -p $basedir

echo --- running GISTIC ---
## input file definitions
segfile=`pwd`/cbs_segmentation_file.txt
refgenefile=`pwd`/refgenefiles/hg18.mat
## call script that sets MCR environment and calls GISTIC executable 
./gistic2_ads -b $basedir -seg $segfile -refgene $refgenefile  -smallmem 1 -broad 1 -brlen 0.5 -conf 0.90 -armpeel 1 -savegene 1 
